# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ankita.ui'
#
# Created: Mon Dec 19 17:02:37 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(596, 500)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frameShape = QtGui.QFrame(self.centralwidget)
        self.frameShape.setFrameShape(QtGui.QFrame.Box)
        self.frameShape.setFrameShadow(QtGui.QFrame.Raised)
        self.frameShape.setObjectName(_fromUtf8("frameShape"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frameShape)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineBtn = QtGui.QPushButton(self.frameShape)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/line.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lineBtn.setIcon(icon)
        self.lineBtn.setIconSize(QtCore.QSize(32, 32))
        self.lineBtn.setCheckable(True)
        self.lineBtn.setAutoExclusive(False)
        self.lineBtn.setObjectName(_fromUtf8("lineBtn"))
        self.gridLayout_2.addWidget(self.lineBtn, 2, 0, 1, 1)
        self.pencilBtn = QtGui.QPushButton(self.frameShape)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/pencil.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pencilBtn.setIcon(icon1)
        self.pencilBtn.setIconSize(QtCore.QSize(32, 32))
        self.pencilBtn.setCheckable(True)
        self.pencilBtn.setAutoExclusive(False)
        self.pencilBtn.setObjectName(_fromUtf8("pencilBtn"))
        self.gridLayout_2.addWidget(self.pencilBtn, 1, 0, 1, 1)
        self.rectBtn = QtGui.QPushButton(self.frameShape)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/rectangle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rectBtn.setIcon(icon2)
        self.rectBtn.setIconSize(QtCore.QSize(32, 32))
        self.rectBtn.setCheckable(True)
        self.rectBtn.setAutoExclusive(False)
        self.rectBtn.setObjectName(_fromUtf8("rectBtn"))
        self.gridLayout_2.addWidget(self.rectBtn, 3, 0, 1, 1)
        self.polygonBtn = QtGui.QPushButton(self.frameShape)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/polygon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.polygonBtn.setIcon(icon3)
        self.polygonBtn.setIconSize(QtCore.QSize(32, 32))
        self.polygonBtn.setCheckable(True)
        self.polygonBtn.setAutoExclusive(False)
        self.polygonBtn.setObjectName(_fromUtf8("polygonBtn"))
        self.gridLayout_2.addWidget(self.polygonBtn, 3, 1, 1, 1)
        self.polylineBtn = QtGui.QPushButton(self.frameShape)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/polyline.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.polylineBtn.setIcon(icon4)
        self.polylineBtn.setIconSize(QtCore.QSize(32, 32))
        self.polylineBtn.setCheckable(True)
        self.polylineBtn.setAutoExclusive(False)
        self.polylineBtn.setObjectName(_fromUtf8("polylineBtn"))
        self.gridLayout_2.addWidget(self.polylineBtn, 2, 1, 1, 1)
        self.brushBtn = QtGui.QPushButton(self.frameShape)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/brush.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brushBtn.setIcon(icon5)
        self.brushBtn.setIconSize(QtCore.QSize(32, 32))
        self.brushBtn.setCheckable(True)
        self.brushBtn.setAutoExclusive(False)
        self.brushBtn.setObjectName(_fromUtf8("brushBtn"))
        self.gridLayout_2.addWidget(self.brushBtn, 1, 1, 1, 1)
        self.ovalBtn = QtGui.QPushButton(self.frameShape)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/oval.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ovalBtn.setIcon(icon6)
        self.ovalBtn.setIconSize(QtCore.QSize(32, 32))
        self.ovalBtn.setCheckable(True)
        self.ovalBtn.setAutoExclusive(False)
        self.ovalBtn.setObjectName(_fromUtf8("ovalBtn"))
        self.gridLayout_2.addWidget(self.ovalBtn, 4, 0, 1, 1)
        self.arcBtn = QtGui.QPushButton(self.frameShape)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/arc.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arcBtn.setIcon(icon7)
        self.arcBtn.setIconSize(QtCore.QSize(32, 32))
        self.arcBtn.setCheckable(True)
        self.arcBtn.setAutoExclusive(False)
        self.arcBtn.setObjectName(_fromUtf8("arcBtn"))
        self.gridLayout_2.addWidget(self.arcBtn, 4, 1, 1, 1)
        self.label = QtGui.QLabel(self.frameShape)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 4)
        self.floodfillBtn = QtGui.QPushButton(self.frameShape)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/floodfill.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.floodfillBtn.setIcon(icon8)
        self.floodfillBtn.setIconSize(QtCore.QSize(32, 32))
        self.floodfillBtn.setCheckable(True)
        self.floodfillBtn.setAutoExclusive(False)
        self.floodfillBtn.setObjectName(_fromUtf8("floodfillBtn"))
        self.gridLayout_2.addWidget(self.floodfillBtn, 1, 2, 1, 2)
        self.verticalLayout.addWidget(self.frameShape)
        self.frameColor = QtGui.QFrame(self.centralwidget)
        self.frameColor.setFrameShape(QtGui.QFrame.Box)
        self.frameColor.setFrameShadow(QtGui.QFrame.Raised)
        self.frameColor.setObjectName(_fromUtf8("frameColor"))
        self.gridLayout = QtGui.QGridLayout(self.frameColor)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelLine = QtGui.QLabel(self.frameColor)
        self.labelLine.setFrameShape(QtGui.QFrame.Box)
        self.labelLine.setText(_fromUtf8(""))
        self.labelLine.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLine.setObjectName(_fromUtf8("labelLine"))
        self.gridLayout.addWidget(self.labelLine, 1, 1, 1, 1)
        self.labelFill = QtGui.QLabel(self.frameColor)
        self.labelFill.setFrameShape(QtGui.QFrame.Box)
        self.labelFill.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFill.setObjectName(_fromUtf8("labelFill"))
        self.gridLayout.addWidget(self.labelFill, 2, 1, 1, 1)
        self.linecolorBtn = QtGui.QRadioButton(self.frameColor)
        self.linecolorBtn.setChecked(True)
        self.linecolorBtn.setObjectName(_fromUtf8("linecolorBtn"))
        self.gridLayout.addWidget(self.linecolorBtn, 1, 0, 1, 1)
        self.fillcolorBtn = QtGui.QRadioButton(self.frameColor)
        self.fillcolorBtn.setObjectName(_fromUtf8("fillcolorBtn"))
        self.gridLayout.addWidget(self.fillcolorBtn, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frameColor)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.frameColor)
        self.zoominBtn = QtGui.QPushButton(self.centralwidget)
        self.zoominBtn.setObjectName(_fromUtf8("zoominBtn"))
        self.verticalLayout.addWidget(self.zoominBtn)
        self.zoomoutBtn = QtGui.QPushButton(self.centralwidget)
        self.zoomoutBtn.setObjectName(_fromUtf8("zoomoutBtn"))
        self.verticalLayout.addWidget(self.zoomoutBtn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollWidget = QtGui.QWidget()
        self.scrollWidget.setGeometry(QtCore.QRect(0, 0, 396, 441))
        self.scrollWidget.setObjectName(_fromUtf8("scrollWidget"))
        self.scrollArea.setWidget(self.scrollWidget)
        self.horizontalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Ankita", None))
        self.lineBtn.setToolTip(_translate("MainWindow", "Straight Line", None))
        self.pencilBtn.setToolTip(_translate("MainWindow", "Pencil", None))
        self.rectBtn.setToolTip(_translate("MainWindow", "Rectangle", None))
        self.polygonBtn.setToolTip(_translate("MainWindow", "Polygon", None))
        self.polylineBtn.setToolTip(_translate("MainWindow", "Polyline", None))
        self.brushBtn.setToolTip(_translate("MainWindow", "Brush", None))
        self.ovalBtn.setToolTip(_translate("MainWindow", "Oval", None))
        self.arcBtn.setToolTip(_translate("MainWindow", "Arc", None))
        self.label.setText(_translate("MainWindow", "<b>Drawing Tools<b>", None))
        self.floodfillBtn.setToolTip(_translate("MainWindow", "Floodfill", None))
        self.labelFill.setText(_translate("MainWindow", "Empty", None))
        self.linecolorBtn.setText(_translate("MainWindow", "Set Line :", None))
        self.fillcolorBtn.setText(_translate("MainWindow", "Set Fill :", None))
        self.label_2.setText(_translate("MainWindow", "<b>Color Palette<b>", None))
        self.zoominBtn.setText(_translate("MainWindow", "Zoom In", None))
        self.zoomoutBtn.setText(_translate("MainWindow", "Zoom Out", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))

import ankita_rc
