INCLUDES = -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4
CFLAGS = 
LIBS = -lQtGui

all:
	g++ -shared $(INCLUDES) $(CFLAGS) $(LIBS) -o ../ankita/floodfill.so floodfill.cpp

clean:
	rm ../ankita/floodfill.so
